/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ./public/assets/models/apart2/apartment.glb 
*/

import React from "react";
import { useGLTF } from "@react-three/drei";

export default function Room2(props) {
	const { nodes, materials } = useGLTF("/assets/models/apart2/apartment.glb");
	return (
		<group {...props} dispose={null}>
			<group rotation={[Math.PI / 2, 0, Math.PI]} scale={-0.009}>
				<group rotation={[Math.PI / 2, 0, 0]}>
					<group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
						<mesh
							geometry={nodes.Box021_ag_0.geometry}
							material={materials.material}
						/>
						<mesh
							geometry={nodes.Box021_demir_0.geometry}
							material={materials.demir}
						/>
						<mesh
							geometry={nodes["Box021_Material_#108_0"].geometry}
							material={materials.Material_108}
						/>
						<mesh
							geometry={nodes["Box021_Material_#97_0"].geometry}
							material={materials.Material_97}
						/>
						<mesh
							geometry={nodes.Box021_mavi_0.geometry}
							material={materials.mavi}
						/>
					</group>
					<group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
						<mesh
							geometry={nodes.fur2_funiture_0.geometry}
							material={materials.funiture}
						/>
						<mesh
							geometry={nodes.fur2_funiture_0001.geometry}
							material={materials.funiture}
						/>
					</group>
					<group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
						<mesh
							geometry={nodes.Refr_BLACK_PLASTIC_0.geometry}
							material={materials.BLACK_PLASTIC}
						/>
						<mesh
							geometry={nodes.Refr_BROWN_MATTE_0.geometry}
							material={materials.BROWN_MATTE}
						/>
						<mesh
							geometry={nodes.Refr_WHITE_PLASTIC_0.geometry}
							material={materials.WHITE_PLASTIC}
						/>
					</group>
					<mesh
						geometry={nodes.Body001_blinn4001_0.geometry}
						material={materials["blinn4.001"]}
						rotation={[-Math.PI / 2, 0, 0]}
						scale={100}
					/>
					<mesh
						geometry={nodes.fur1001_Material_0.geometry}
						material={materials["Material.001"]}
						rotation={[-Math.PI / 2, 0, 0]}
						scale={100}
					/>
					<mesh
						geometry={nodes["glass_02_-_Default_0"].geometry}
						material={materials["02_-_Default"]}
						rotation={[-Math.PI / 2, 0, 0]}
						scale={100}
					/>
					<mesh
						geometry={nodes.group14_hm_result_mesh1_blinn6_0.geometry}
						material={materials.blinn6}
						rotation={[-Math.PI / 2, 0, 0]}
						scale={100}
					/>
					<mesh
						geometry={nodes.group14_Light_pCylinder3_blinn7_0.geometry}
						material={materials.blinn7}
						rotation={[-Math.PI / 2, 0, 0]}
						scale={100}
					/>
					<mesh
						geometry={nodes.Handle_blinn5001_0.geometry}
						material={materials["blinn5.001"]}
						rotation={[-Math.PI / 2, 0, 0]}
						scale={100}
					/>
					<mesh
						geometry={nodes.pCube7_lambert1_0.geometry}
						material={materials.lambert1}
						rotation={[-Math.PI / 2, 0, 0]}
						scale={100}
					/>
					<mesh
						geometry={nodes.sofa2_pCube4_lambert3_0.geometry}
						material={materials.lambert3}
						rotation={[-Math.PI / 2, 0, 0]}
						scale={100}
					/>
					<mesh
						geometry={nodes.sofa_1_pCube6_lambert2_0.geometry}
						material={materials.lambert2}
						rotation={[-Math.PI / 2, 0, 0]}
						scale={100}
					/>
					<mesh
						geometry={nodes.stove_modern_smart_stove1_0.geometry}
						material={materials.modern_smart_stove1}
						rotation={[-Math.PI / 2, 0, 0]}
						scale={100}
					/>
					<mesh
						geometry={nodes.wall1_wall_0.geometry}
						material={materials.wall}
						rotation={[-Math.PI / 2, 0, 0]}
						scale={100}
					/>
					<mesh
						geometry={nodes.wood7_wood5_0.geometry}
						material={materials.wood5}
						rotation={[-Math.PI / 2, 0, 0]}
						scale={100}
					/>
				</group>
			</group>
		</group>
	);
}

useGLTF.preload("/assets/models/apart2/apartment.glb");
