/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/assets/models/apart2/apartment.glb -T 
Files: public/assets/models/apart2/apartment.glb [12.16MB] > /home/mem0real/Desktop/coding/react-three-fiber-projects/r3f-movement/apartment-transformed.glb [1.17MB] (90%)
*/

import React, { useContext, useEffect } from "react";
import { useGLTF } from "@react-three/drei";
import { useZus } from "../../utils/store";
import { RefContext } from "../../components/3d-components/MyScene";

export function Room4(props) {
	const { nodes, materials } = useGLTF(
		"/assets/models/apartment-transformed.glb"
	);

	const { toggleModelLoaded } = useZus();
	const canvasRef = useContext(RefContext);

	useEffect(() => {
		toggleModelLoaded();
	}, []);

	const handleClick = async () => {
		const canvas = canvasRef?.current;

		if (!canvas.pointerLockElement)
			setTimeout(async () => await canvas.requestPointerLock(), 500);
	};
	return (
		<group {...props} dispose={null} onClick={handleClick}>
			<mesh
				geometry={nodes.Body001_blinn4001_0.geometry}
				material={materials["blinn4.001"]}
				rotation={[-Math.PI / 2, 0, -Math.PI]}
				scale={[-0.928, 0.928, 0.928]}
			/>
			<mesh
				geometry={nodes.Box021_ag_0.geometry}
				material={materials.PaletteMaterial001}
				rotation={[-Math.PI / 2, 0, -Math.PI]}
				scale={[-0.928, 0.928, 0.928]}
			/>
			<mesh
				geometry={nodes.fur2_funiture_0.geometry}
				material={materials.funiture}
				rotation={[-Math.PI / 2, 0, -Math.PI]}
				scale={[-0.928, 0.928, 0.928]}
			/>
			<mesh
				geometry={nodes.group14_hm_result_mesh1_blinn6_0.geometry}
				material={materials.blinn6}
				rotation={[-Math.PI / 2, 0, -Math.PI]}
				scale={[-0.928, 0.928, 0.928]}
			/>
			<mesh
				geometry={nodes.group14_Light_pCylinder3_blinn7_0.geometry}
				material={materials.blinn7}
				rotation={[-Math.PI / 2, 0, -Math.PI]}
				scale={[-0.928, 0.928, 0.928]}
			/>
			<mesh
				geometry={nodes.Handle_blinn5001_0.geometry}
				material={materials["blinn5.001"]}
				rotation={[-Math.PI / 2, 0, -Math.PI]}
				scale={[-0.928, 0.928, 0.928]}
			/>
			<mesh
				geometry={nodes.pCube7_lambert1_0.geometry}
				material={materials.lambert1}
				rotation={[-Math.PI / 2, 0, -Math.PI]}
				scale={[-0.928, 0.928, 0.928]}
			/>
			<mesh
				geometry={nodes.sofa2_pCube4_lambert3_0.geometry}
				material={materials.lambert3}
				rotation={[-Math.PI / 2, 0, -Math.PI]}
				scale={[-0.928, 0.928, 0.928]}
			/>
			<mesh
				geometry={nodes.sofa_1_pCube6_lambert2_0.geometry}
				material={materials.lambert2}
				rotation={[-Math.PI / 2, 0, -Math.PI]}
				scale={[-0.928, 0.928, 0.928]}
			/>
			<mesh
				geometry={nodes.stove_modern_smart_stove1_0.geometry}
				material={materials.modern_smart_stove1}
				rotation={[-Math.PI / 2, 0, -Math.PI]}
				scale={[-0.928, 0.928, 0.928]}
			/>
			<mesh
				geometry={nodes.wall1_wall_0.geometry}
				material={materials.wall}
				rotation={[-Math.PI / 2, 0, -Math.PI]}
				scale={[-0.928, 0.928, 0.928]}
			/>
			<mesh
				geometry={nodes.wood7_wood5_0.geometry}
				material={materials.wood5}
				rotation={[-Math.PI / 2, 0, -Math.PI]}
				scale={[-0.928, 0.928, 0.928]}
			/>
		</group>
	);
}

useGLTF.preload("/assets/models/apartment-transformed.glb");
