/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ./public/assets/models/apart3/scaled.glb --transform 
Files: ./public/assets/models/apart3/scaled.glb [2.3MB] > /home/mem0real/Desktop/coding/react-three-fiber-projects/r3f-movement/scaled-transformed.glb [258.09KB] (89%)
*/

import React from "react";
import { useGLTF } from "@react-three/drei";

export default function Scaled(props) {
	const { nodes, materials } = useGLTF(
		"/assets/models/apart3/scaled-transformed.glb"
	);
	return (
		<group {...props} dispose={null}>
			<mesh
				geometry={nodes.Material2016.geometry}
				material={materials.material}
				position={[3.527, 1.114, -0.401]}
				scale={0.028}
			/>
			<mesh
				geometry={nodes.Material2056.geometry}
				material={materials.Translucent_Glass_Gray_4}
				position={[-2.542, 2.169, -5.373]}
				scale={0.028}
			/>
			<mesh
				geometry={nodes.Material2057.geometry}
				material={materials["0003_DeepPink"]}
				position={[3.079, -0.001, 0.438]}
				rotation={[-Math.PI / 2, 0, 1.335]}
				scale={[0.019, 0.028, 0.024]}
			/>
			<mesh
				geometry={nodes.Material2060.geometry}
				material={materials.Wood_Floor_Dark_1}
				position={[-5.396, -0.568, 4.569]}
				rotation={[-Math.PI / 2, 0, 0]}
				scale={0.028}
			/>
		</group>
	);
}

useGLTF.preload("/assets/models/apart3/scaled-transformed.glb");
